name: post-to-ghost
descriptiom: "Post to Ghost instance once target folder have new post"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    require: ture
    default: ${{ github.token }}
  GHOST_BASE_API_URL:
    description: "Ghost base api url"
    require: false
  GHOST_CONTENT_API_TOKEN:
    description: "Ghost content api token"
    require: false
  GHOST_ADMIN_API_TOKEN:
    description: "Ghost admin api token"
    require: false
  TARGET_FOLDER:
    description: "Where store articles"
    require: false

outputs:
  modified:
    description: >
      Array of modified files.

runs:
  using: "node16"
  main: "dist/index.js"
