name: Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: env

      - name: Print events.json
        run: cat "$GITHUB_EVENT_PATH"

  build:
    runs-on: ubuntu-latest
    needs: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: run
        name: Run the action
        uses: ./
        with:
          TARGET_FOLDER: test_docs

